export const JOB_STATUSES = {
  QUEUED: 'QUEUED',
  SCHEDULED: 'SCHEDULED',
  RUNNING: 'RUNNING',
};

export const JOB_EXECUTION_STATUSES = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  SUCCESS: 'SUCCESS',
  FAIL: 'FAIL',
};
